# Generated by Django 2.0.6 on 2019-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('powers', models.CharField(max_length=200)),
                ('power_type', models.CharField(max_length=200)),
                ('alignment', models.CharField(max_length=200)),
                ('example', models.CharField(max_length=200)),
            ],
        ),
    ]
